name: onboarding_alarm_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.1
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  intl: ^0.20.2
  get: ^4.7.2
  shared_preferences: ^2.5.3
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/screenshots/
